### PR TITLE
[BUGFIX] for SerializeToJson Handler

### PR DESCRIPTION
**Pull request by larsroettig**
The handler not working for wee_tex fields

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/data-migration-tool?pullRequest=245) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/data-migration-tool?pullRequest=245) before we can accept your contribution.<br/>

**Comment by victor-v-rad** [comment]
Thank you @larsroettig for your contribution.
We will investigate this issue

**Comment by victor-v-rad** [comment]
@larsroettig 
I have tested all weee_tax_applied fields in sales tables. In all cases (quotes, invoices, orders) this field had serialized data. So it should always be universalized. Please point out if I missed something

**Comment by larsroettig** [comment]
@victor-v-rad in this case was notserialized data see my phpunit testcase. And if run the test without the fix a Fatal Error exits.

**Comment by larsroettig** [comment]
@victor-v-rad  why you are not merge this pull  request ?

**Comment by victor-v-rad** [comment]
@larsroettig SerializeToJson Handler is used not only for weee_tax_applied fields but many others and it is still seems weee module always do serialization before saving (see Magento 1 \Mage_Weee_Helper_Data::setApplied)

**Pull request closed without merging**
