### PR TITLE
Update Mysql.php

### PR DESCRIPTION
**Pull request by Polar77**
Fix migrate utf-8 characters

### CODE REVIEW

**Comment by ilol** [comment]
@Polar77 Thanks!

**Comment by aarondong2005** [comment]
Only need to change MySQL.php to migrate utf-8?

**Comment by Polar77** [comment]
Yes

**Comment by aarondong2005** [comment]
Well, your solution doesn't work for me. I end up with this one but some modification.
https://github.com/magento/data-migration-tool/issues/148

**Comment by victor-v-rad** [comment]
Thank you @Polar77 for for contriburion! The issue was fixed in a different way within this two commits ce958b4 e4abd7c

**Pull request closed without merging**
