### PR TITLE
[#695] Migrate Settings Failing XSD Validation

### PR DESCRIPTION
**Pull request by PivitParkour94**
### Description

Added switch statement to validate config/settings files correctly. Increased the error output to help with debugging.
As this is a CLI tool, I can't see any issues with have more verbose output.

### Fixed Issues (if relevant)
1. magento/data-migration-tool#695: Migrate Settings Failing XSD Validation Opensource-to-Opensource

### Manual testing scenarios

1. Install data migration tool <composer require magento/data-migration-tool:2.3.1> on existing, working Magento 2.3.1 installation (running in production deploy mode) 
2. cp ./vendor/magento/data-migration-tool/etc/opensource-to-opensource/settings.xml.dist ./vendor/magento/data-migration-tool/etc/opensource-to-opensource/settings.xml
3. bin/magento -vvv migrate:settings ./vendor/magento/data-migration-tool/etc/opensource-to-opensource/settings.xml
4. See settings have migrated instead of getting a vague validation error

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/data-migration-tool?pullRequest=696) <br/>All committers have signed the CLA.

**Comment by PivitParkour94** [comment]
It would be good to get this merged in before the magento/data-migration-tool gets too many additions to avoid an annoying merge conflict

@victor-v-rad were you able to do anything about this?

**Comment by victor-v-rad** [comment]
Thank you @PivitParkour94 for this high quality PR!  Right now I'm preparing new release and will process your PR right after it. Thank you again.

**Comment by victor-v-rad** [comment]
Hi @PivitParkour94 

I have not found in our [documentation](https://devdocs.magento.com/guides/v2.3/migration/migration-migrate-settings.html) about using settings.xml as an argument in that command line
```
bin/magento -vvv migrate:settings ./vendor/magento/data-migration-tool/etc/opensource-to-opensource/settings.xml
```
it should be your config.xml file. For example
```
bin/magento -vvv migrate:settings ./vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.8/config.xml
```

Maybe you used some unreliable source of information about using of the tool.

**Comment by PivitParkour94** [comment]
>Specify the new name of the settings file for mapping. To do that, change the <settings_map_file> tag in the path/to/config.xml file.

Ah, well, that makes sense. I missed the definition of the `settings_map_file`
What a shame, should've read the manual. 

Thanks for your time. Sorry this isn't actually an issue. I'll close it up

**Comment by victor-v-rad** [comment]
@PivitParkour94 Yeah, at first glance using settings.xml in migrate:settings command seems quite reasonable. I really appreciate your time and willing to make a contribution anyway. Thank you!

**Pull request closed without merging**
