### PR TITLE
Hotfix/1.9.3.8 1.9.3.4 references

### PR DESCRIPTION
**Pull request by clivewalkden**
Hi,

Just been running the migration tool and spotted some links which needed updating for the config.xml.dist files. Below is my commit message.

Updated some references to map-tier-pricing.xml.dist in the 1.9.3.6-1.9.3.8 and 1.14.3.6-1.14.3.8 config.xml.dist files

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/data-migration-tool?pullRequest=548) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/data-migration-tool?pullRequest=548) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: victor-v-rad<br/>:x: clivewalkden

**Comment by victor-v-rad** [comment]
You you are right. Could you please create a new issue about it in 
https://github.com/magento/data-migration-tool/issues
and link it to this pull request

**Comment by clivewalkden** [comment]
Done, thanks for looking at this

**Comment by victor-v-rad** [comment]
Internal ticket MAGETWO-93233 to process it

**Pull request merged**
