### PR TITLE
magento/data-migration-tool#282: Record structure does not match prov…

### PR DESCRIPTION
**Pull request by devamitbera**
Trying to migrate some Eav attribute data and I was getting the exception error. 

[Undefined offset: 9 in vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 55  ](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/Eav/Data.php#L553)

The issue was rasied for an attribute which does not belong any attribute sets.
So, **I  have added at a condition [at](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/Eav/Data.php#L552)** 

`isset($attributeSetGroups[$record->getValue('attribute_set_id')][$attributeGroupCode]) with $attributes[$attributeId]['attribute_code'] == $attributeCode`

```
            if ($attributes[$attributeId]['attribute_code'] == $attributeCode
                && isset($attributeSetGroups[$record->getValue('attribute_set_id')][$attributeGroupCode])
            ) 
```

That  resolve the issue and other attributes was successfully migrated

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/data-migration-tool?pullRequest=289) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/data-migration-tool?pullRequest=289) before we can accept your contribution.<br/>

**Comment by devamitbera** [comment]
Request to all, Please don't push this changes at the main branch.

this exception is occurring for  **shipment_type, price**   when these two attributes have assigned to attribute group.

I am cross checking all the things and get back to

**Comment by ihor-sviziev** [comment]
@devamitbera if these changes are not good - you could close your pull request.

**Comment by devamitbera** [comment]
Sure, @ihor-sviziev , i will do it today

**Comment by victor-v-rad** [comment]
in 2.2.0 it was fixed

**Pull request closed without merging**
